### ISSUE TITLE
Panic in Main

### ISSUE THREAD

**Issue by appilon** [radeksimko/go-mod-diff#1]
```
❯ GO111MODULE=on go-mod-diff vendor.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1265dfc]

goroutine 1 [running]:
github.com/radeksimko/go-mod-diff/diff.CompareGoModWithGovendor(0x0, 0xc0000b6410, 0xc0000b07c0, 0x0, 0x0, 0x10)
	/Users/alex/git/go/src/github.com/radeksimko/go-mod-diff/diff/diff.go:73 +0x21c
main.main()
	/Users/alex/git/go/src/github.com/radeksimko/go-mod-diff/main.go:37 +0x207
```
updated to tip of master and go this error running the tool, let me know if you want to see the vendor.json and go.mod files

**Comment by appilon** [comment]
😑 I was on the wrong branch when running go-mod-diff sorry!!!!
